function Invoke-Help {
    param($Ctx)
    
    Write-Warning "Usage: jmp <command> [args]"
    Write-Info ""
    Write-Info "Commands:"
    Write-Info "  scan                    - Discover Java installations (PATH-ES-first, then fd, then fallback)"
    Write-Info "  list                    - List all discovered Java"
    Write-Info "  use <version> [vendor]  - Switch Java version for current session"
    Write-Info "  unuse                   - Clear Java environment from current session"
    Write-Info "  pin <version> [vendor] [scope] - Pin Java version to user/system environment"
    Write-Info "  unpin [scope]           - Remove pinned Java from user/system environment"
    Write-Info "  current                 - Show current JAVA_HOME"
    Write-Info "  version                 - Show script version"
    Write-Info "  help                    - Show this help"
    Write-Info ""
    Write-Info "Examples:"
    Write-Info "  jmp use 21              - Switch to Java 21 for current session"
    Write-Info "  jmp use 21 temurin      - Switch to Temurin Java 21 for current session"
    Write-Info "  jmp unuse               - Clear Java from current session"
    Write-Info "  jmp pin 21              - Pin Java 21 to user environment (default)"
    Write-Info "  jmp pin 21 system       - Pin Java 21 to system environment (requires admin)"
    Write-Info "  jmp pin 21 temurin user - Pin Temurin Java 21 to user environment"
    Write-Info "  jmp unpin               - Remove pinned Java from user environment"
    Write-Info "  jmp unpin system        - Remove pinned Java from system environment (requires admin)"
    Write-Info ""
    Write-Info "Options:"
    Write-Info "  -debug                  - Enable debug output"
    Write-Info "  -fallback [1|2]         - Control scan fallback mode:"
    Write-Info "                            -fallback 1 = Skip Everything, use fd (if available)"
    Write-Info "                            -fallback 2 = Direct fallback scan (skip Everything and fd)"
    Write-Info "                            -fallback   = Same as -fallback 2"
    Show-Header
}