function Invoke-Help {
    param($Ctx)

    Write-Warning "Usage: jmp <command> [args]"
    Write-Info ""
    Write-Info "Commands:"
    Write-Info "  scan    - Discover Java installations"
    Write-Info "  list    - List all discovered Java"
    Write-Info "  use     - Switch Java version for current session"
    Write-Info "  unuse   - Clear Java environment from current session"
    Write-Info "  pin     - Pin Java version to user/system environment"
    Write-Info "  unpin   - Remove pinned Java from user/system environment"
    Write-Info "  current - Show current JAVA_HOME"
    Write-Info "  which   - Show which Java would be selected (without switching)"
    Write-Info "  info    - Show detailed Java installation info"
    Write-Info "  doctor  - Run diagnostics and health checks"
    Write-Info "  reset   - Reset JMP to clean state (clear env vars and cache)"
    Write-Info "  version - Show script version"
    Write-Info "  help    - Show this help"
    Write-Info ""
    Write-Info "Examples:"
    Write-Info "  jmp scan              # Scan for Java installations (default mode)"
    Write-Info "  jmp scan -light       # Fast scan using registry and common paths"
    Write-Info "  jmp scan -deep        # Comprehensive scan using fd tool"
    Write-Info "  jmp use 21 temurin    # Use Temurin Java 21"
    Write-Info "  jmp pin 21 system     # Pin Java 21 to system (needs admin)"
    Write-Info "  jmp which 17           # Show which Java 17 would be selected"
    Write-Info "  jmp info 17           # Show detailed info for Java 17"
    Write-Info "  jmp doctor            # Run health diagnostics"
    Write-Info "  jmp reset             # Reset to clean state (clear env vars + cache)"
    Write-Info "  jmp reset --system    # Reset including system JAVA_HOME (needs admin)"
    Write-Info "  jmp reset --force     # Reset without confirmation prompt"
    Write-Info ""
    Write-Info "Options:"
    Write-Info "  -debug                  - Enable debug output"
    Write-Info "  -light                  - Use light scan mode (fast, no external dependencies)"
    Write-Info "  -deep                   - Use deep scan mode (comprehensive, requires fd.exe)"
    Write-Info "  -no-parallel-download  - Disable parallel download for fd (slower but more stable)"
    Write-Info ""
    Write-Info "Run 'jmp <command>' without args for command-specific help"
    Show-Header
}